<?php

/**
 * @file
 * Contains unical.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function unical_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the unical module.
    case 'help.page.unical':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Unical') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function unical_theme() {
  return [
    'unical' => [
      'render element' => 'children',
    ],
  ];
}
